security:
  basic:
    enabled: true # turn off securing our application endpoints

management:
  security:
    enabled: true # turn off securing the actuator endpoints

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG 

pooling: false
